---
title: "Homework 2 - Spatial Regression"
author: "Richard Barad, Jarred Randall, Dave Drennan"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


```{r import_libraries}
library(sf)
library(tidyverse)
library(kableExtra)
library(spatialreg)
library(spdep)
library(gridExtra)
library(whitestrap)
library(lmtest)
library(tseries)
library(spgwr)
library(tmap)
```

```{r read_data echo=FALSE}

data <- st_read('./Data/RegressionData.shp')

```

# Spatial Autocorrelation

## Global Moran's I

```{r queen_neighboors, results='hide'}
queen<-spdep::poly2nb(data, row.names=data$POLY_ID)
```

```{r warning=FALSE, message=FALSE, cache=FALSE}

queenlist<-nb2listw(queen, style = 'W')

moranMC<-moran.mc(data$LNMEDHVAL, queenlist, nsim=999, alternative="two.sided")  #We use 999 permutations

#Draws distribution of Moran's I's calculated from randomly permuted values
# Here, we draw a red vertical line at the observed value of our Moran's I

ggplot()+
  geom_histogram(aes(moranMC$res),binwidth = 0.005)+
  xlim(-1,1)+
  geom_vline(xintercept=moranMC$statistic,color='red',linewidth=1)+
  annotate("text",x=0.6, y=150,color='red',label=paste("Moran's I = ",as.character(round(moranMC$statistic,2))))+
  labs(x="Moran's I value",y='Count')+
  theme_bw()

```

## Local Moran's I

```{r localmoransI}
#Run local moran's I (LISA) 

LISA<-localmoran(data$LNMEDHVAL, queenlist)
data_LISA <-cbind(data, as.data.frame(LISA))

quadrant<-vector(mode='numeric', length=323)
m.prop<-data$LNMEDHVAL - mean(data$LNMEDHVAL)
m.local<-LISA[,1]-mean(LISA[,1])
quadrant[m.prop >0 & m.local>0]<-'4' #high MEDHHINC, high clustering
quadrant[m.prop <0 & m.local<0]<-'1' #low MEDHHINC, low clustering
quadrant[m.prop <0 & m.local>0]<-'2' #low MEDHINC, high clustering
quadrant[m.prop >0 & m.local<0]<-'3' #high MEDHHINC, low clustering
quadrant[LISA[,5]>0.05]<-0

data_LISA <-cbind(data, as.data.frame(LISA), as.data.frame(quadrant))
```


```{r Morans_I_map, warning=FALSE, message=FALSE, cache=FALSE, fig.height = 6,fig.width=10}
grid.arrange(ncol=3,
             
ggplot()+
  geom_sf(data=data,aes(fill=LNMEDHVAL))+
  scale_fill_viridis_c(option='rocket',direction=-1)+
  theme_void()+
  theme(panel.background = element_rect(fill='white'),
        legend.position = c(0.80, 0.21),
        plot.title = element_text(hjust = 0.5))+
  ggtitle("Natural Log of Median Home Value"),

ggplot()+
  geom_sf(data=data_LISA,aes(fill = cut(Pr.z....E.Ii.., breaks = c(0,0.01,0.05,0.5,1))))+
  scale_fill_manual(values = c('#990000','#ef6548','#fdbb84','#fef0d9'),
                    labels=c('0 - 0.01','0.01 - 0.05','0.05 - 0.5','0.5 - 1'),
                    name='p value')+
  theme_void()+
  theme(panel.background = element_rect(fill='white'),
        legend.position = c(0.80, 0.21),
        plot.title = element_text(hjust = 0.5))+
  ggtitle("Local Morans I (p value)"),
             
ggplot()+
  geom_sf(data=data_LISA,aes(fill=quadrant))+
  scale_fill_manual(values=c('grey80','lightblue','blue','pink','red'),
                    labels=c("Insignificant","Low-High","Low-Low","High-Low","High-High"),
                    name='Significant Cluster')+
  theme_void()+
  theme(panel.background = element_rect(fill='white'),
        legend.position = c(0.80, 0.21),
        plot.title = element_text(hjust = 0.5))+
  ggtitle("Significant Clusters of High/Low Values")
)
```

# A Review of OLS Regression and Assumptions: 

## OLS Results

```{r ols_regression}

reg <-lm(LNMEDHVAL ~  PCTVACANT + PCTSINGLES + PCTBACHMOR + LNNBELPOV, data=data)

summary(reg)
```

## Heteroscedasticity tests

```{r hetersecadsticity tests}
#Prints the results of the Breusch-Pagan Test to assess whether heteroscedasticity is present (package: lmtest)
bptest(reg, studentize=FALSE)
#Prints the results of the Koenker-Bassett Test (also known as the Studentized Breusch-Pagan Test) to assess whether heteroscedasticity is present (package: lmtest)
bptest(reg)       
#Prints the results of the White Test to assess whether heteroscedasticity is present (package: whitestrap)
white_test(reg)
```


```{r scatter_plot}

data <- data %>%
  mutate(predictions = predict(reg,data),
        residual = LNMEDHVAL - predictions,
        stdres = rstandard(reg))

ggplot()+
  geom_point(data=data,aes(x=predictions,y=stdres),size=0.4
             )+
  labs(x='Predicted Values',y='Standardized Residuals')+
  ggtitle('Predicted Values vs. Standardized Residuals')+
  theme_bw()

```

## Normality of errors (Jarque-Bera test)

``` {r jarque_bera_test}
#Prints the results of the Jarque-Bera Test to assess whether residuals are normal (package: tseries)
jarque.bera.test(data$residual)
```

``` {r histogram}

ggplot()+
  geom_histogram(data=data,aes(x=stdres),bins=100,color='white',fill='grey50')+
  labs(x='Standardized residual')+
  theme_bw()

```

## Spatial Autocorelation Checks

### Morans I plot 1

```{r warning=FALSE, message=FALSE, cache=FALSE}

data$resnb<-sapply(queen, function(x) mean(data$stdres[x]))

res.lm <- lm(formula=data$resnb ~ data$stdres)
summary(res.lm)

#This code is all to get the p-value and beta coefficient from the regression summary so that we can annotate thoose values on the scatter plot. It might not be necessary and we can just show the regression summary in addition to the scatter plot. I added it because the GeoDa results include an annotation with the coefficient.

p_value <- summary(res.lm)$coefficients[2,4]
coefficient= summary(res.lm)$coefficients[2,1]
p_value = format(p_value, scientific = TRUE)

ggplot(data=data,aes(x=stdres,y=resnb))+
  geom_point(size=0.4)+
  geom_smooth(method = "lm", se = FALSE,color='blue',linewidth=0.5)+
  annotate("text",x=4, y=-2,color='red',label=paste("Coefficient: ",as.character(round(coefficient,3))))+
  annotate("text",x=4, y=-2.3,color='red',label=paste("p-value: ",as.character((p_value))))+
  labs(x='Standardized Residuals',y='Spatially Lagged Standardized Residuals')+
  ggtitle('Standardized Resiudals vs Lagged Standardized Residuals')+
  theme_bw()
```
## Morans I Permutation Results

```{r warning=FALSE, message=FALSE, cache=FALSE}

moranMC_OLSres<-moran.mc(data$stdres, queenlist, nsim=999, alternative="two.sided")  #We use 999 permutations

#Draws distribution of Moran's I's calculated from randomly permuted values
# Here, we draw a red vertical line at the observed value of our Moran's I

ggplot()+
  geom_histogram(aes(moranMC_OLSres$res),binwidth = 0.005)+
  xlim(-1,1)+
  geom_vline(xintercept=moranMC_OLSres$statistic,color='red',linewidth=1)+
  annotate("text",x=0.6, y=150,color='red',label=paste("Moran's I = ",as.character(round(moranMC_OLSres$statistic,2))))+
  labs(x="Moran's I value",y='Count')+
  theme_bw()
```

# Spatial Lag Regression

```{r warning=FALSE, message=FALSE, cache=FALSE}
lagreg<-lagsarlm(formula=LNMEDHVAL ~ LNNBELPOV + PCTBACHMOR + PCTSINGLES + PCTVACANT, data=data, queenlist)
summary(lagreg)
LR.Sarlm(lagreg, reg) #Here lagreg is the SL output; reg is the OLS output
#Prints the results of the Breusch-Pagan Test to assess whether heteroscedasticity is present (package: lmtest)
bptest.Sarlm(lagreg, studentize=FALSE)
#Prints the results of the Koenker-Bassett Test (also known as the Studentized Breusch-Pagan Test) to assess whether heteroscedasticity is present (package: lmtest)
bptest.Sarlm(lagreg)       
#Prints the results of the Jarque-Bera Test to assess whether residuals are normal (package: tseries)
jarque.bera.test(lagreg$residuals)
```

```{r warning=FALSE, message=FALSE, cache=FALSE}
reslag<-lagreg$residuals
lagMoranMc<-moran.mc(reslag, queenlist,999, alternative="two.sided")
lagMoranMc

ggplot()+
  geom_histogram(aes(lagMoranMc$res),binwidth = 0.005)+
  xlim(-1,1)+
  geom_vline(xintercept=lagMoranMc$statistic,color='red',linewidth=1)+
  annotate("text",x=0.6, y=150,color='red',label=paste("Moran's I = ",as.character(round(lagMoranMc$statistic,2))))+
  labs(x="Moran's I value",y='Count')+
  theme_bw()

```

# Spatial Error Regression

```{r warning=FALSE, message=FALSE, cache=FALSE}
errreg<-errorsarlm(formula=LNMEDHVAL ~ LNNBELPOV + PCTBACHMOR + PCTSINGLES + PCTVACANT, data=data, queenlist)
reserr<-residuals(errreg)
errresnb<-sapply(queen, function(x) mean(reserr[x]))
summary(errreg)
LR.Sarlm(errreg, reg)
#Prints the results of the Breusch-Pagan Test to assess whether heteroscedasticity is present (package: lmtest)
bptest.Sarlm(errreg, studentize=FALSE)
#Prints the results of the Koenker-Bassett Test (also known as the Studentized Breusch-Pagan Test) to assess whether heteroscedasticity is present (package: lmtest)
bptest.Sarlm(errreg)       
#Prints the results of the Jarque-Bera Test to assess whether residuals are normal (package: tseries)
jarque.bera.test(errreg$residuals)
```

```{r warning=FALSE, message=FALSE, cache=FALSE}
errMoranMc<-moran.mc(reserr, queenlist, 999, alternative="two.sided")
errMoranMc

ggplot()+
  geom_histogram(aes(errMoranMc$res),binwidth = 0.005)+
  xlim(-1,1)+
  geom_vline(xintercept=errMoranMc$statistic,color='red',linewidth=1)+
  annotate("text",x=0.6, y=150,color='red',label=paste("Moran's I = ",as.character(round(errMoranMc$statistic,2))))+
  labs(x="Moran's I value",y='Count')+
  theme_bw()

```

# GWR

```{r warning=FALSE, message=FALSE, cache=FALSE}
#Setting an adaptive bandwidth
datas <- as(data, 'Spatial')  #These analyses are easier to do when the data are of the SpatialPolygonsDataFrame class
class (datas)
bw<-gwr.sel(formula=LNMEDHVAL ~ LNNBELPOV + PCTBACHMOR + PCTSINGLES + PCTVACANT, 
            data=datas,
            method = "aic",
            adapt = TRUE)
bw
```

```{r warning=FALSE, message=FALSE, cache=FALSE}
gwrmodel<-gwr(formula=LNMEDHVAL ~ LNNBELPOV + PCTBACHMOR + PCTSINGLES + PCTVACANT,
              data=datas,
              adapt = bw, #adaptive bandwidth determined by proportion of observations accounted for
              gweight=gwr.Gauss,
              se.fit=TRUE, #to return local standard errors
              hatmatrix = TRUE)
gwrmodel

```



```{r warning=FALSE, message=FALSE, cache=FALSE}
summary(gwrmodel$SDF)
```

```{r warning=FALSE, message=FALSE, cache=FALSE}

gwrMoranMc<-moran.mc(gwrmodel$SDF@data$gwr.e, queenlist, 999, alternative="two.sided")

gwrMoranMc  #We use 999 permutations

#Draws distribution of Moran's I's calculated from randomly permuted values
# Here, we draw a red vertical line at the observed value of our Moran's I

ggplot()+
  geom_histogram(aes(moranMC_OLSres$res),binwidth = 0.005)+
  xlim(-1,1)+
  geom_vline(xintercept=moranMC_OLSres$statistic,color='red',linewidth=1)+
  annotate("text",x=0.6, y=150,color='red',label=paste("Moran's I = ",as.character(round(moranMC_OLSres$statistic,2))))+
  labs(x="Moran's I value",y='Count')+
  theme_bw()

```



```{r warning=FALSE, message=FALSE, cache=FALSE}
gwrresults<-as.data.frame(gwrmodel$SDF)
datas$coefPCTVACANTst<-gwrresults$PCTVACANT/gwrresults$PCTVACANT_se
datas$coefPCTBACHMORst<-gwrresults$PCTBACHMOR/gwrresults$PCTBACHMOR_se
datas$coefPCTSINGLESst<-gwrresults$PCTSINGLES/gwrresults$PCTSINGLES_se
datas$coefLNNBELPOVst<-gwrresults$LNNBELPOV/gwrresults$LNNBELPOV_se


datas$gwrE<-gwrresults$gwr.e
datas$localR2<-gwrresults$localR2

coefLNNBELPOV<-tm_shape(datas)+
  tm_fill(col='coefLNNBELPOVst', breaks=c(-Inf, -6, -4, -2, 0, 2, 4, 6, Inf), title='Standardized coefficient of coefLNNBELPOV', 
          palette ='-RdBu')+
  tm_layout(frame=FALSE, title = 'Number of Households Below Poverty Line (Log)')

coefPCTVACANT<-tm_shape(datas)+
  tm_fill(col='coefPCTVACANTst', breaks=c(-Inf, -6, -4, -2, 0, 2, 4, 6, Inf), title='Standardized coefficient of PCTVACANT', 
          palette='-RdBu')+
  tm_layout(frame=FALSE, title = 'Percentage of Vacant Housing')

coefPCTSINGLES<-tm_shape(datas)+
  tm_fill(col='coefPCTSINGLESst', breaks=c(-Inf, -6, -4, -2, 0, 2, 4, 6, Inf), title='Standardized coefficient of coefPCTSINGLES', 
          palette ='-RdBu')+
  tm_layout(frame=FALSE, title = 'Percentage of Single Family Houses')

coefPCTBACHMOR<-tm_shape(datas)+
  tm_fill(col='coefPCTBACHMORst', breaks=c(-Inf, -6, -4, -2, 0, 2, 4, 6, Inf), title='Standardized coefficient of coefPCTBACHMOR', 
          palette ='-RdBu')+
  tm_layout(frame=FALSE, title = 'Percent of Bachelor’s Degree')

tmap_arrange(coefPCTBACHMOR, coefPCTVACANT,coefLNNBELPOV,coefPCTSINGLES,  ncol=2)

```
```{r warning=FALSE, message=FALSE, cache=FALSE}
tm_shape(datas)+
  tm_fill(col='localR2',  breaks=c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7), n=5, palette = 'Blues')+
  tm_layout(frame=FALSE)
```

