---
title: "HW3-LogisticRegression"
author: "Richard Barad, Dave Drennan, Jarred Randall"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r warning=FALSE, message=FALSE, cache=FALSE}
library(aod)
library(rms)
library(gmodels)
library(nnet)
library(DAAG)
library(ROCR)
library(knitr)
library(kableExtra)
library(xtable)
library(dplyr)
library(tidyverse)
library(corrr)
```

```{r warning=FALSE, message=FALSE, cache=FALSE}
data <- read.csv("./Data/LogisticRegressionData.csv")

```

## Proportion of Crashes Involving a Drinking Driver

```{r}

DRINKING_D.tab <- table(data$DRINKING_D)

kable(prop.table(DRINKING_D.tab), col.names = c("Drinking Driver", "Proportion"), 
      caption = "Proportion of Crashes Involving a Drinking Driver") %>%
  kable_styling(c("striped"), full_width = T, position = "left", font_size = 12)

```



## cross-tabulation between our dependent variable and binary predictors

```{r crosstab, warning=FALSE, message=FALSE, cache=FALSE, results='hide'}

# We need to figure out the best way to make the table he is asking for

ct1_pct <- CrossTable(data$DRINKING_D, data$FATAL_OR_M, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$prop.row[3:4]
ct2_pct <- CrossTable(data$DRINKING_D, data$OVERTURNED, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$prop.row[3:4]
ct3_pct <- CrossTable(data$DRINKING_D, data$CELL_PHONE, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$prop.row[3:4]
ct4_pct <- CrossTable(data$DRINKING_D, data$SPEEDING, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$prop.row[3:4]
ct5_pct <- CrossTable(data$DRINKING_D, data$AGGRESSIVE, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$prop.row[3:4]
ct6_pct <- CrossTable(data$DRINKING_D, data$DRIVER1617, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$prop.row[3:4]
ct7_pct <- CrossTable(data$DRINKING_D, data$DRIVER65PLUS, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$prop.row[3:4]

ct1_n <- CrossTable(data$DRINKING_D, data$FATAL_OR_M, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$t[3:4]
ct2_n <- CrossTable(data$DRINKING_D, data$OVERTURNED, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$t[3:4]
ct3_n <- CrossTable(data$DRINKING_D, data$CELL_PHONE, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$t[3:4]
ct4_n <- CrossTable(data$DRINKING_D, data$SPEEDING, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$t[3:4]
ct5_n <- CrossTable(data$DRINKING_D, data$AGGRESSIVE, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$t[3:4]
ct6_n <- CrossTable(data$DRINKING_D, data$DRIVER1617, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$t[3:4]
ct7_n <- CrossTable(data$DRINKING_D, data$DRIVER65PLUS, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE)$t[3:4]
```

```{r chi_squared, warning=FALSE, message=FALSE, cache=FALSE, results='hide'}
ct_chi1 <- CrossTable(data$FATAL_OR_M, data$DRINKING_D, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)$chisq$p.value
ct_chi2 <- CrossTable(data$OVERTURNED, data$DRINKING_D, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)$chisq$p.value
ct_chi3 <- CrossTable(data$CELL_PHONE, data$DRINKING_D, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)$chisq$p.value
ct_chi4 <- CrossTable(data$SPEEDING, data$DRINKING_D, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)$chisq$p.value
ct_chi5 <- CrossTable(data$AGGRESSIVE, data$DRINKING_D, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)$chisq$p.value
ct_chi6 <- CrossTable(data$DRIVER1617, data$DRINKING_D, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)$chisq$p.value
ct_chi7 <- CrossTable(data$DRIVER65PLUS, data$DRINKING_D, prop.r=FALSE, prop.t=FALSE, prop.chisq=FALSE, chisq=TRUE)$chisq$p.value

chi_vector <- c(ct_chi1, ct_chi2, ct_chi3, ct_chi4, ct_chi5, ct_chi6, ct_chi7)

chi_table <- cbind(chi_vector,variable=c('FATAL_OR_M','OVERTURNED','CELL_PHONE','SPEEDING','AGGRESSIVE','DRIVER1617','DRIVER65PLUS')) %>%
  as_data_frame()
```

```{r}
df_cross_tab_pct <- cbind(DRINKING_D = c(0,1),ct1_pct, ct2_pct, ct3_pct, ct4_pct, ct5_pct, ct6_pct, ct7_pct) %>%
  as_data_frame() %>%
  rename(FATAL_OR_M = ct1_pct,
         OVERTURNED = ct2_pct,
         CELL_PHONE = ct3_pct,
         SPEEDING = ct4_pct,
         AGGRESSIVE = ct5_pct,
         DRIVER1617 = ct6_pct,
         DRIVER65PLUS = ct7_pct) %>%
  gather(variable, value, -DRINKING_D) %>%
  spread(key=DRINKING_D, value=value) %>%
  rename("No_Drinking_pct" = "0",
         "Drinking_pct" = "1")


cbind(DRINKING_D = c(0,1),ct1_n, ct2_n, ct3_n, ct4_n, ct5_n, ct6_n, ct7_n) %>%
  as_data_frame() %>%
  rename(FATAL_OR_M = ct1_n,
         OVERTURNED = ct2_n,
         CELL_PHONE = ct3_n,
         SPEEDING = ct4_n,
         AGGRESSIVE = ct5_n,
         DRIVER1617 = ct6_n,
         DRIVER65PLUS = ct7_n) %>%
  gather(variable, value, -DRINKING_D) %>%
  spread(key=DRINKING_D, value=value) %>%
  rename("No_Drinking_n" = "0",
         "Drinking_n" = "1") %>%
  left_join(.,df_cross_tab_pct,by='variable') %>%
  mutate(Total = No_Drinking_n + Drinking_n,
         Drinking_pct = round(Drinking_pct * 100,2),
         No_Drinking_pct = round(No_Drinking_pct * 100,2)) %>%
  select(variable, No_Drinking_n, No_Drinking_pct, Drinking_n, Drinking_pct,Total) %>%
  left_join(.,chi_table,by='variable') %>%
  kbl(col.names = c('Variable','N','%','N','%','Total','χ2 p-value')) %>%
  kable_classic_2() %>%
  add_header_above(header=c(" "=1,"No Alchoal Involved (DRINKING_D=0)"=2,"Alchoal Involved (DRINKING_D=1)"=2, " "=2))

```



## Calcuate Means for Continuous Variables

```{r}

data_group_mean <- data %>% dplyr::select(DRINKING_D,PCTBACHMOR,MEDHHINC) %>%
  group_by(DRINKING_D) %>% summarise_at(vars(PCTBACHMOR,MEDHHINC),mean) %>%
  gather(key='variable', value='mean', -DRINKING_D) %>%
  spread(key=DRINKING_D,value=mean) %>%
  rename("No_Drinking_mean" = "0",
         "Drinking_mean" = "1")

data_group_sd <- data %>% dplyr::select(DRINKING_D,PCTBACHMOR,MEDHHINC) %>%
  group_by(DRINKING_D) %>% summarise_at(vars(PCTBACHMOR,MEDHHINC),mean) %>%
  gather(key='variable', value='sd', -DRINKING_D) %>%
  spread(key=DRINKING_D,value=sd) %>%
  rename("No_Drinking_sd" = "0",
         "Drinking_sd" = "1")

```

```{r t_test}
t_PCTBACHMORE <- t.test(data$PCTBACHMOR~data$DRINKING_D)$p.value
t_MEDHHINC <- t.test(data$MEDHHINC~data$DRINKING_D)$p.value

t_vector = c(t_MEDHHINC,t_PCTBACHMORE)

cbind(data_group_mean,data_group_sd %>% dplyr::select(-variable),t_vector) %>%
  select(variable, Drinking_mean, Drinking_sd, No_Drinking_mean, No_Drinking_sd,t_vector) %>%
  kbl(col.names = c('Variable','Mean','SD','Mean','SD','t-test p-value')) %>%
  kable_classic_2() %>%
  add_header_above(header=c(" " = 1, "Drinking" = 2,"No Drinking"=2, " "=1))

```

## Correlation

```{r pearson, echo=FALSE}

predictors <- data %>% dplyr::select(-CRN,-AREAKEY,-DRINKING_D)

predictors %>% 
  correlate() %>% 
  autoplot() +
  geom_text(aes(label = round(r,digits=2)),size = 3)
```
